# Generated by Django 3.2.16 on 2022-11-18 19:50

from django.db import migrations, models
import multiprocessing.sharedctypes


class Migration(migrations.Migration):

    dependencies = [
        ('My_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=multiprocessing.sharedctypes.Value, upload_to=None),
        ),
    ]
